/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaquinasIndexRouteImport } from './routes/maquinas.index'
import { Route as MaquinasIdRouteImport } from './routes/maquinas.$id'

const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinasIndexRoute = MaquinasIndexRouteImport.update({
  id: '/maquinas/',
  path: '/maquinas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinasIdRoute = MaquinasIdRouteImport.update({
  id: '/maquinas/$id',
  path: '/maquinas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/maquinas/$id': typeof MaquinasIdRoute
  '/maquinas/': typeof MaquinasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/maquinas/$id': typeof MaquinasIdRoute
  '/maquinas': typeof MaquinasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/maquinas/$id': typeof MaquinasIdRoute
  '/maquinas/': typeof MaquinasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criar' | '/maquinas/$id' | '/maquinas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criar' | '/maquinas/$id' | '/maquinas'
  id: '__root__' | '/' | '/criar' | '/maquinas/$id' | '/maquinas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarRoute: typeof CriarRoute
  MaquinasIdRoute: typeof MaquinasIdRoute
  MaquinasIndexRoute: typeof MaquinasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquinas/': {
      id: '/maquinas/'
      path: '/maquinas'
      fullPath: '/maquinas/'
      preLoaderRoute: typeof MaquinasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquinas/$id': {
      id: '/maquinas/$id'
      path: '/maquinas/$id'
      fullPath: '/maquinas/$id'
      preLoaderRoute: typeof MaquinasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarRoute: CriarRoute,
  MaquinasIdRoute: MaquinasIdRoute,
  MaquinasIndexRoute: MaquinasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
