/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedModelosRouteImport } from './routes/_authenticated.modelos'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated.criar'
import { Route as AuthenticatedMaquinasIndexRouteImport } from './routes/_authenticated.maquinas.index'
import { Route as AuthenticatedMaquinasIdRouteImport } from './routes/_authenticated.maquinas.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedModelosRoute = AuthenticatedModelosRouteImport.update({
  id: '/_authenticated/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/_authenticated/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMaquinasIndexRoute =
  AuthenticatedMaquinasIndexRouteImport.update({
    id: '/_authenticated/maquinas/',
    path: '/maquinas/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMaquinasIdRoute = AuthenticatedMaquinasIdRouteImport.update({
  id: '/_authenticated/maquinas/$id',
  path: '/maquinas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/criar': typeof AuthenticatedCriarRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/': typeof AuthenticatedIndexRoute
  '/maquinas/$id': typeof AuthenticatedMaquinasIdRoute
  '/maquinas/': typeof AuthenticatedMaquinasIndexRoute
}
export interface FileRoutesByTo {
  '/criar': typeof AuthenticatedCriarRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/': typeof AuthenticatedIndexRoute
  '/maquinas/$id': typeof AuthenticatedMaquinasIdRoute
  '/maquinas': typeof AuthenticatedMaquinasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/modelos': typeof AuthenticatedModelosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/maquinas/$id': typeof AuthenticatedMaquinasIdRoute
  '/_authenticated/maquinas/': typeof AuthenticatedMaquinasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/criar' | '/modelos' | '/' | '/maquinas/$id' | '/maquinas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/criar' | '/modelos' | '/' | '/maquinas/$id' | '/maquinas'
  id:
    | '__root__'
    | '/_authenticated/criar'
    | '/_authenticated/modelos'
    | '/_authenticated/'
    | '/_authenticated/maquinas/$id'
    | '/_authenticated/maquinas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedModelosRoute: typeof AuthenticatedModelosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMaquinasIdRoute: typeof AuthenticatedMaquinasIdRoute
  AuthenticatedMaquinasIndexRoute: typeof AuthenticatedMaquinasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/modelos': {
      id: '/_authenticated/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthenticatedModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/maquinas/': {
      id: '/_authenticated/maquinas/'
      path: '/maquinas'
      fullPath: '/maquinas/'
      preLoaderRoute: typeof AuthenticatedMaquinasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/maquinas/$id': {
      id: '/_authenticated/maquinas/$id'
      path: '/maquinas/$id'
      fullPath: '/maquinas/$id'
      preLoaderRoute: typeof AuthenticatedMaquinasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedModelosRoute: AuthenticatedModelosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMaquinasIdRoute: AuthenticatedMaquinasIdRoute,
  AuthenticatedMaquinasIndexRoute: AuthenticatedMaquinasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
